<?php
# This file was automatically generated by the MediaWiki 1.36.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

# $wgShowSQLErrors = true;
# $wgShowDBErrorBacktrace = true;
$wgShowExceptionDetails  = true;
# $wgShowDebug  = true;
# $wgDevelopmentWarnings  = true;

$wgSitename = "Meta Wiki";
$wgMetaNamespace = "Meta_Wiki";
$wgServer = "https://meta.hypoverse.org";
$wgDBname = "meta_wiki";

$wgScriptPath = "/w";
## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "https://meta.hypoverse.org/w/images/general/Meta/7/77/Hypoverse_Meta_Wiki_Logo.png" ];
$wgFavicon = "https://meta.hypoverse.org/w/images/general/Meta/6/64/Favicon.ico";

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgSVGConverter = 'ImageMagick';
$wgImageMagickConvertCommand = "/usr/bin/convert";
// $wgUploadDirectory = "/mnt/hypoverse_images/images/general/Meta";
// $wgUploadPath = "{$wgScriptPath}/images/general/Meta";
// $wgTmpDirectory = "/mnt/hypoverse_images/images/general/Meta/temp";

$wgUploadDirectory = "/mnt/h_images/images/general/Meta";
$wgUploadPath = "{$wgScriptPath}/images/general/Meta";
$wgTmpDirectory = "/mnt/h_images/images/general/Meta/temp";
$wgThumbnailEpoch = 20230708220648;
$wgCacheEpoch = 20230708220648;
setlocale(LC_NUMERIC, "C");
$wgShellLocale = "C.UTF-8";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgSecretKey = "e746aba971aee6e1c6a7398b40201cacad8dc3d8490a1f49879822e95f6a39e7";
$wgUpgradeKey = "69d16866b5ef3464";

require_once "Local_Skins.php";
require_once "Local_Permissions.php";

// $wgApplyGlobalBlocks = false; # debugging
// $wgGlobalBlockingApplyUsernameBlocks = false; # debugging
$wgMessageCommonsIsCommons = true; // MessageCommons

# Per wiki permission overrides