<?php
# This file was automatically generated by the MediaWiki 1.36.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgSitename = "Hypothetical Events";
$wgMetaNamespace = "Hypothetical_Events";
$wgServer = "https://events.hypoverse.org";
$wgDBname = "events_wiki";

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "https://meta.hypoverse.org/w/images/general/Meta/b/b4/Hypoverse_Events_Wiki_Logo.png" ];
$wgFavicon = "https://meta.hypoverse.org/w/images/general/Meta/6/64/Favicon.ico";

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
// $wgUploadDirectory = "/mnt/hypoverse_images/images/general/Events";
// $wgUploadPath = "{$wgScriptPath}/images/general/Events";
// $wgTmpDirectory = "/mnt/hypoverse_images/images/general/Events/temp";

$wgUploadDirectory = "/mnt/h_images/images/general/Events";
$wgUploadPath = "{$wgScriptPath}/images/general/Events";
$wgTmpDirectory = "/mnt/h_images/images/general/Events/temp";
$wgThumbnailEpoch = 20230708220648;
$wgCacheEpoch = 20230708220648;
setlocale(LC_NUMERIC, "C");
$wgShellLocale = "C.UTF-8";


$wgThumbnailEpoch = 20221216025513;
$wgCacheEpoch = 20221216025513;
$wgMaxShellMemory = 307200;
setlocale(LC_NUMERIC, "C");
$wgShellLocale = "C.UTF-8";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgSecretKey = "e24dd08f88efa59e2043c4e8f2b1bff15218cfd9837e6514d2edfd234c12fbc8";
$wgUpgradeKey = "3693bea6a28b5b21";

require_once "Local_Skins.php";
require_once "Local_Permissions.php";

# Per wiki permission overrides

## Unset Consul and Social-Moderator groups for this wiki
unset( $wgGroupPermissions['consul'] );
unset( $wgRevokePermissions['consul'] );
unset( $wgAddGroups['consul'] );
unset( $wgRemoveGroups['consul'] );
unset( $wgGroupsAddToSelf['consul'] );
unset( $wgGroupsRemoveFromSelf['consul'] ); 

$wgExtensionFunctions[] = function() use ( &$wgGroupPermissions)  {
    unset( $wgGroupPermissions['social-moderator'] );
};
unset( $wgGroupPermissions['social-moderator'] );
unset( $wgRevokePermissions['social-moderator'] );
unset( $wgAddGroups['social-moderator'] );
unset( $wgRemoveGroups['social-moderator'] );
unset( $wgGroupsAddToSelf['social-moderator'] );
unset( $wgGroupsRemoveFromSelf['social-moderator'] ); 

## Junior Administrator Group
$wgGroupPermissions['junioradmin'] = $wgGroupPermissions['user'];
$wgGroupPermissions['junioradmin']['autoconfirmed'] = true;
$wgGroupPermissions['junioradmin']['autopatrol'] = true;
$wgGroupPermissions['junioradmin']['delete'] = true;
$wgGroupPermissions['junioradmin']['deletedhistory'] = true;
$wgGroupPermissions['junioradmin']['deletedtext'] = true;
$wgGroupPermissions['junioradmin']['editinterface'] = true;
$wgGroupPermissions['junioradmin']['editprotected'] = true;
$wgGroupPermissions['junioradmin']['editsemiprotected'] = true;
$wgGroupPermissions['junioradmin']['editsitecss'] = true;
$wgGroupPermissions['junioradmin']['editsitejs'] = true;
$wgGroupPermissions['junioradmin']['editsitejson'] = true;
$wgGroupPermissions['junioradmin']['edittemplates'] = true;
$wgGroupPermissions['junioradmin']['extconfirmed'] = true;
$wgGroupPermissions['junioradmin']['import'] = true;
$wgGroupPermissions['junioradmin']['importupload'] = true;
$wgGroupPermissions['junioradmin']['modchat'] = true;
$wgGroupPermissions['junioradmin']['movefile'] = true;
$wgGroupPermissions['junioradmin']['noratelimit'] = true;
$wgGroupPermissions['junioradmin']['purge'] = true;
$wgGroupPermissions['junioradmin']['patrol'] = true;
$wgGroupPermissions['junioradmin']['patrolmarks'] = true;
$wgGroupPermissions['junioradmin']['protect'] = true;
$wgGroupPermissions['junioradmin']['rollback'] = true;
$wgGroupPermissions['junioradmin']['skipcaptcha'] = true;
$wgGroupPermissions['junioradmin']['suppressredirect'] = true;
$wgGroupPermissions['junioradmin']['undelete'] = true;

$wgGroupsRemoveFromSelf['junioradmin'] = array( 'junioradmin' );

## Administrator Group
$wgGroupPermissions['sysop'] = $wgGroupPermissions['junioradmin'];
$wgGroupPermissions['sysop']['abusefilter-log-private'] = true;
$wgGroupPermissions['sysop']['abusefilter-modify'] = true;
$wgGroupPermissions['sysop']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['sysop']['abusefilter-privatedetails'] = false;
$wgGroupPermissions['sysop']['abusefilter-revert'] = true;
$wgGroupPermissions['sysop']['abusefilter-view-private'] = false;
$wgGroupPermissions['sysop']['adminlinks'] = true;
$wgGroupPermissions['sysop']['block'] = true;
$wgGroupPermissions['sysop']['createaccount'] = false;
$wgGroupPermissions['sysop']['deletebatch'] = true;
$wgGroupPermissions['sysop']['editinterface'] = true;
$wgGroupPermissions['sysop']['editsitecss'] = true;
$wgGroupPermissions['sysop']['editsitejs'] = true;
$wgGroupPermissions['sysop']['editsitejson'] = true;
$wgGroupPermissions['sysop']['edittemplates'] = true;
$wgGroupPermissions['sysop']['extconfirmed'] = true;
$wgGroupPermissions['sysop']['import'] = true;
$wgGroupPermissions['sysop']['importupload'] = true;
$wgGroupPermissions['sysop']['ipblock-exempt'] = true;
$wgGroupPermissions['sysop']['managechangetags'] = true;
$wgGroupPermissions['sysop']['markbotedits'] = true;
$wgGroupPermissions['sysop']['move'] = true;
$wgGroupPermissions['sysop']['movefile'] = true;
$wgGroupPermissions['sysop']['move-categorypages'] = true;
$wgGroupPermissions['sysop']['move-rootuserpages'] = true;
$wgGroupPermissions['sysop']['move-subpages'] = true;
$wgGroupPermissions['sysop']['nuke'] = false;
$wgGroupPermissions['sysop']['purge'] = true;
$wgGroupPermissions['sysop']['reupload'] = true;
$wgGroupPermissions['sysop']['reupload-own'] = true;
$wgGroupPermissions['sysop']['reupload-shared'] = true;
$wgGroupPermissions['sysop']['skipcaptcha'] = true;
$wgGroupPermissions['sysop']['tboverride'] = false;
$wgGroupPermissions['sysop']['titleblacklistlog'] = false;
$wgGroupPermissions['sysop']['unblockself'] = true;
$wgGroupPermissions['sysop']['upload'] = true;
$wgGroupPermissions['sysop']['upload_by_url'] = true;
$wgGroupPermissions['sysop']['modchat'] = true;

$wgAddGroups['sysop'] = array( 'rollback', 'confirmed', 'autopatrolled', 'flooder', 'bannedfromchat' );
$wgRemoveGroups['sysop'] = array( 'rollback', 'confirmed', 'autopatrolled', 'flooder', 'bannedfromchat' );
$wgGroupsAddToSelf['sysop'] = array( 'flooder' );
$wgGroupsRemoveFromSelf['sysop'] = array( 'sysop', 'flooder' );

## Senior Administrator Group
$wgGroupPermissions['senioradmin'] = $wgGroupPermissions['sysop'];
$wgGroupPermissions['senioradmin']['abusefilter-log-private'] = true;
$wgGroupPermissions['senioradmin']['abusefilter-modify'] = true;
$wgGroupPermissions['senioradmin']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['senioradmin']['abusefilter-privatedetails'] = false;
$wgGroupPermissions['senioradmin']['abusefilter-revert'] = true;
$wgGroupPermissions['senioradmin']['abusefilter-view-private'] = false;
$wgGroupPermissions['senioradmin']['adminlinks'] = true;
$wgGroupPermissions['senioradmin']['block'] = true;
$wgGroupPermissions['senioradmin']['createaccount'] = false;
$wgGroupPermissions['senioradmin']['deletebatch'] = true;
$wgGroupPermissions['senioradmin']['editinterface'] = true;
$wgGroupPermissions['senioradmin']['editsitecss'] = true;
$wgGroupPermissions['senioradmin']['editsitejs'] = true;
$wgGroupPermissions['senioradmin']['editsitejson'] = true;
$wgGroupPermissions['senioradmin']['edittemplates'] = true;
$wgGroupPermissions['senioradmin']['extconfirmed'] = true;
$wgGroupPermissions['senioradmin']['import'] = true;
$wgGroupPermissions['senioradmin']['importupload'] = true;
$wgGroupPermissions['senioradmin']['ipblock-exempt'] = true;
$wgGroupPermissions['senioradmin']['managechangetags'] = true;
$wgGroupPermissions['senioradmin']['markbotedits'] = true;
$wgGroupPermissions['senioradmin']['move'] = true;
$wgGroupPermissions['senioradmin']['movefile'] = true;
$wgGroupPermissions['senioradmin']['move-categorypages'] = true;
$wgGroupPermissions['senioradmin']['move-rootuserpages'] = true;
$wgGroupPermissions['senioradmin']['move-subpages'] = true;
$wgGroupPermissions['senioradmin']['nuke'] = false;
$wgGroupPermissions['senioradmin']['purge'] = true;
$wgGroupPermissions['senioradmin']['reupload'] = true;
$wgGroupPermissions['senioradmin']['reupload-own'] = true;
$wgGroupPermissions['senioradmin']['reupload-shared'] = true;
$wgGroupPermissions['senioradmin']['skipcaptcha'] = true;
$wgGroupPermissions['senioradmin']['tboverride'] = false;
$wgGroupPermissions['senioradmin']['titleblacklistlog'] = false;
$wgGroupPermissions['senioradmin']['unblockself'] = true;
$wgGroupPermissions['senioradmin']['upload'] = true;
$wgGroupPermissions['senioradmin']['upload_by_url'] = true;

$wgAddGroups['senioradmin'] = array( 'junioradmin', 'rollback', 'confirmed', 'autopatrolled', 'flooder', 'bannedfromchat' );
$wgRemoveGroups['senioradmin'] = array( 'junioradmin', 'rollback', 'confirmed', 'autopatrolled', 'flooder', 'bannedfromchat' );
$wgGroupsAddToSelf['senioradmin'] = array( 'flooder' );
$wgGroupsRemoveFromSelf['senioradmin'] = array( 'senioradmin', 'flooder' );

## Junior Bureaucrat Group
$wgGroupPermissions['jrbureaucrat'] = $wgGroupPermissions['sysop'];
$wgGroupPermissions['jrbureaucrat']['abusefilter-log-private'] = true;
$wgGroupPermissions['jrbureaucrat']['abusefilter-modify'] = true;
$wgGroupPermissions['jrbureaucrat']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['jrbureaucrat']['abusefilter-privatedetails'] = false;
$wgGroupPermissions['jrbureaucrat']['abusefilter-revert'] = true;
$wgGroupPermissions['jrbureaucrat']['abusefilter-view-private'] = false;
$wgGroupPermissions['jrbureaucrat']['adminlinks'] = true;
$wgGroupPermissions['jrbureaucrat']['block'] = true;
$wgGroupPermissions['jrbureaucrat']['bureaucrat'] = true;
$wgGroupPermissions['jrbureaucrat']['createaccount'] = false;
$wgGroupPermissions['jrbureaucrat']['deletelogentry'] = true;
$wgGroupPermissions['jrbureaucrat']['deleterevision'] = true;
$wgGroupPermissions['jrbureaucrat']['editinterface'] = true;
$wgGroupPermissions['jrbureaucrat']['editsitecss'] = true;
$wgGroupPermissions['jrbureaucrat']['editsitejs'] = true;
$wgGroupPermissions['jrbureaucrat']['editsitejson'] = true;
$wgGroupPermissions['jrbureaucrat']['edittemplates'] = true;
$wgGroupPermissions['jrbureaucrat']['extconfirmed'] = true;
$wgGroupPermissions['jrbureaucrat']['import'] = true;
$wgGroupPermissions['jrbureaucrat']['importupload'] = true;
$wgGroupPermissions['jrbureaucrat']['ipblock-exempt'] = true;
$wgGroupPermissions['jrbureaucrat']['managechangetags'] = true;
$wgGroupPermissions['jrbureaucrat']['markbotedits'] = true;
$wgGroupPermissions['jrbureaucrat']['move'] = true;
$wgGroupPermissions['jrbureaucrat']['movefile'] = true;
$wgGroupPermissions['jrbureaucrat']['nuke'] = true;
# $wgGroupPermissions['jrbureaucrat']['protectsite'] = true;
$wgGroupPermissions['jrbureaucrat']['skipcaptcha'] = true;
$wgGroupPermissions['jrbureaucrat']['unblockself'] = true;
$wgGroupPermissions['jrbureaucrat']['upload'] = true;
$wgGroupPermissions['jrbureaucrat']['upload_by_url'] = true;
$wgGroupPermissions['jrbureaucrat']['userrights'] = false;

$wgAddGroups['jrbureaucrat'] = array( 'senioradmin', 'sysop', 'junioradmin', 'social-moderator', 'rollback', 'confirmed', 'autopatrolled', 'bot', 'flooder', 'bannedfromchat' );
$wgRemoveGroups['jrbureaucrat'] = array( 'senioradmin', 'sysop', 'junioradmin', 'social-moderator', 'rollback', 'confirmed', 'autopatrolled', 'bot', 'flooder', 'bannedfromchat' );
$wgGroupsRemoveFromSelf['jrbureaucrat'] = array( 'jrbureaucrat' );

## Bureaucrat Group
$wgGroupPermissions['bureaucrat'] = $wgGroupPermissions['sysop'];
$wgGroupPermissions['bureaucrat']['abusefilter-log-private'] = true;
$wgGroupPermissions['bureaucrat']['abusefilter-modify'] = true;
$wgGroupPermissions['bureaucrat']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['bureaucrat']['abusefilter-privatedetails'] = false;
$wgGroupPermissions['bureaucrat']['abusefilter-revert'] = true;
$wgGroupPermissions['bureaucrat']['abusefilter-view-private'] = false;
$wgGroupPermissions['bureaucrat']['adminlinks'] = true;
$wgGroupPermissions['bureaucrat']['block'] = true;
$wgGroupPermissions['bureaucrat']['editbureaucratprotected '] = true;
$wgGroupPermissions['bureaucrat']['createaccount'] = false;
$wgGroupPermissions['bureaucrat']['deletelogentry'] = true;
$wgGroupPermissions['bureaucrat']['deleterevision'] = true;
$wgGroupPermissions['bureaucrat']['editinterface'] = true;
$wgGroupPermissions['bureaucrat']['editsitecss'] = true;
$wgGroupPermissions['bureaucrat']['editsitejs'] = true;
$wgGroupPermissions['bureaucrat']['editsitejson'] = true;
$wgGroupPermissions['bureaucrat']['edittemplates'] = true;
$wgGroupPermissions['bureaucrat']['extconfirmed'] = true;
$wgGroupPermissions['bureaucrat']['import'] = true;
$wgGroupPermissions['bureaucrat']['importupload'] = true;
$wgGroupPermissions['bureaucrat']['ipblock-exempt'] = true;
$wgGroupPermissions['bureaucrat']['managechangetags'] = true;
$wgGroupPermissions['bureaucrat']['markbotedits'] = true;
$wgGroupPermissions['bureaucrat']['move'] = true;
$wgGroupPermissions['bureaucrat']['movefile'] = true;
$wgGroupPermissions['bureaucrat']['nuke'] = true;
# $wgGroupPermissions['bureaucrat']['protectsite'] = true;
$wgGroupPermissions['bureaucrat']['skipcaptcha'] = true;
$wgGroupPermissions['bureaucrat']['unblockself'] = true;
$wgGroupPermissions['bureaucrat']['upload'] = true;
$wgGroupPermissions['bureaucrat']['upload_by_url'] = true;
$wgGroupPermissions['bureaucrat']['userrights'] = false;

$wgAddGroups['bureaucrat'] = array( 'jrbureaucrat', 'senioradmin', 'sysop', 'junioradmin', 'social-moderator', 'rollback', 'confirmed', 'autopatrolled', 'bot', 'flooder', 'bannedfromchat' );
$wgRemoveGroups['bureaucrat'] = array( 'jrbureaucrat', 'senioradmin', 'sysop', 'junioradmin', 'social-moderator', 'rollback', 'confirmed', 'autopatrolled', 'bot', 'flooder', 'bannedfromchat' );
$wgGroupsRemoveFromSelf['bureaucrat'] = array( 'bureaucrat' );


## Senior Bureaucrat Group
$wgGroupPermissions['srbureaucrat'] = $wgGroupPermissions['sysop'];
$wgGroupPermissions['srbureaucrat']['abusefilter-log-private'] = true;
$wgGroupPermissions['srbureaucrat']['abusefilter-modify'] = true;
$wgGroupPermissions['srbureaucrat']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['srbureaucrat']['abusefilter-privatedetails'] = false;
$wgGroupPermissions['srbureaucrat']['abusefilter-revert'] = true;
$wgGroupPermissions['srbureaucrat']['abusefilter-view-private'] = false;
$wgGroupPermissions['srbureaucrat']['adminlinks'] = true;
$wgGroupPermissions['srbureaucrat']['block'] = true;
$wgGroupPermissions['srbureaucrat']['editbureaucratprotected'] = true;
$wgGroupPermissions['srbureaucrat']['createaccount'] = false;
$wgGroupPermissions['srbureaucrat']['deletelogentry'] = true;
$wgGroupPermissions['srbureaucrat']['deleterevision'] = true;
$wgGroupPermissions['srbureaucrat']['editinterface'] = true;
$wgGroupPermissions['srbureaucrat']['editsitecss'] = true;
$wgGroupPermissions['srbureaucrat']['editsitejs'] = true;
$wgGroupPermissions['srbureaucrat']['editsitejson'] = true;
$wgGroupPermissions['srbureaucrat']['edittemplates'] = true;
$wgGroupPermissions['srbureaucrat']['extconfirmed'] = true;
$wgGroupPermissions['srbureaucrat']['import'] = true;
$wgGroupPermissions['srbureaucrat']['importupload'] = true;
$wgGroupPermissions['srbureaucrat']['ipblock-exempt'] = true;
$wgGroupPermissions['srbureaucrat']['managechangetags'] = true;
$wgGroupPermissions['srbureaucrat']['markbotedits'] = true;
$wgGroupPermissions['srbureaucrat']['move'] = true;
$wgGroupPermissions['srbureaucrat']['movefile'] = true;
$wgGroupPermissions['srbureaucrat']['nuke'] = true;
# $wgGroupPermissions['srbureaucrat']['protectsite'] = true;
$wgGroupPermissions['srbureaucrat']['skipcaptcha'] = true;
$wgGroupPermissions['srbureaucrat']['unblockself'] = true;
$wgGroupPermissions['srbureaucrat']['upload'] = true;
$wgGroupPermissions['srbureaucrat']['upload_by_url'] = true;
$wgGroupPermissions['srbureaucrat']['userrights'] = false;

$wgAddGroups['srbureaucrat'] = array( 'bureaucrat', 'jrbureaucrat', 'senioradmin', 'sysop', 'junioradmin', 'social-moderator', 'rollback', 'confirmed', 'autopatrolled', 'bot', 'flooder', 'bannedfromchat' );
$wgRemoveGroups['srbureaucrat'] = array( 'bureaucrat', 'jrbureaucrat', 'senioradmin', 'sysop', 'junioradmin', 'social-moderator', 'rollback', 'confirmed', 'autopatrolled', 'bot', 'flooder', 'bannedfromchat' );
$wgGroupsRemoveFromSelf['srbureaucrat'] = array( 'srbureaucrat' );

# Staff
$wgAddGroups['staff'] = array( 'sysop-global', 'srbureaucrat', 'bureaucrat', 'jrbureaucrat', 'senioradmin', 'sysop', 'junioradmin', 'social-moderator', 'rollback', 'autopatrolled', 'confirmed', 'locked', 'bot-global', 'bot', 'flooder', 'bannedfromchat' );
$wgRemoveGroups['staff'] = array( 'sysop-global', 'srbureaucrat', 'bureaucrat', 'jrbureaucrat', 'senioradmin', 'sysop', 'junioradmin', 'social-moderator', 'rollback', 'autopatrolled', 'confirmed', 'locked', 'bot-global', 'bot', 'flooder', 'bannedfromchat' );
$wgGroupsRemoveFromSelf['staff'] = array( 'staff' );

# IT Staff
$wgGroupPermissions['SRE']['apihighlimits'] = true;
$wgGroupPermissions['SRE']['editcontentmodel'] = true;
$wgGroupPermissions['SRE']['editinterface'] = true;
$wgGroupPermissions['SRE']['edit-restricted-interface'] = true;
$wgGroupPermissions['SRE']['editsitecss'] = true;
$wgGroupPermissions['SRE']['editsitejs'] = true;
$wgGroupPermissions['SRE']['editsitejson'] = true;
$wgGroupPermissions['SRE']['edittemplates'] = true;
$wgGroupPermissions['SRE']['editusercss'] = false;
$wgGroupPermissions['SRE']['edituserjs'] = false;
$wgGroupPermissions['SRE']['edituserjson'] = false;
$wgGroupPermissions['SRE']['noratelimit'] = true;
$wgGroupPermissions['SRE']['tech'] = true; 
$wgGroupPermissions['SRE']['purge'] = true;
$wgGroupPermissions['SRE']['sre'] = true;
$wgGroupPermissions['SRE']['writeapi'] = true;

$wgAddGroups['SRE'] = false;
$wgRemoveGroups['SRE'] = false;
$wgGroupsRemoveFromSelf['SRE'] = array( 'SRE' );

# Manager(s)
$wgAddGroups['manager'] = true;
$wgRemoveGroups['manager'] = true;